### ISSUE TITLE
npm run dev won't run (Internal Server Error)

### ISSUE THREAD

**Issue by mrEckendonk** [Highfivery/nextjs-starter#19]
Following instructions, getting stuck at this point.
Using JetBrains IDE (WebStorm) but never had any problem with JetBrains

```
$ npm run dev

> nextjs-starter@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from D:\Projects\others\nextjs-starter\.env
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

error - [stylelint] Class extends value undefined is not a constructor or null
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 283 ms (247 modules)
error - Error: Cannot find module 'D:\Projects\others\nextjs-starter\.next\fallback-build-manifest.json'
Require stack:
- D:\Projects\others\nextjs-starter\node_modules\next\dist\server\load-components.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\server\next-server.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\server\dev\next-dev-server.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\server\next.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\server\lib\start-server.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\cli\next-dev.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\lib\commands.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\bin\next
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at mod._resolveFilename (D:\Projects\others\nextjs-starter\node_modules\next\dist\build\webpack\require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.loadDefaultErrorComponents (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\dev\next-dev-server.js:1062:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.renderErrorToResponse (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:1178:40)
    at async DevServer.renderToResponse (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:1048:30)
    at async DevServer.pipe (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:407:25)
    at async Object.fn (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\next-server.js:759:21)
    at async Router.execute (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\router.js:253:36)
    at async DevServer.run (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:384:29)
    at async DevServer.run (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\dev\next-dev-server.js:743:20)
    at async DevServer.handleRequest (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:322:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\load-components.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\next-server.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\dev\\next-dev-server.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\next.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\cli\\next-dev.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\lib\\commands.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\bin\\next'
  ]
}
Error: Cannot find module 'D:\Projects\others\nextjs-starter\.next\fallback-build-manifest.json'
Require stack:
- D:\Projects\others\nextjs-starter\node_modules\next\dist\server\load-components.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\server\next-server.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\server\dev\next-dev-server.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\server\next.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\server\lib\start-server.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\cli\next-dev.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\lib\commands.js
- D:\Projects\others\nextjs-starter\node_modules\next\dist\bin\next
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at mod._resolveFilename (D:\Projects\others\nextjs-starter\node_modules\next\dist\build\webpack\require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.loadDefaultErrorComponents (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\dev\next-dev-server.js:1062:43)
    at async DevServer.renderErrorToResponse (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:1178:40)
    at async pipe.req.req (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:1075:30)
    at async DevServer.pipe (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:407:25)
    at async DevServer.run (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\dev\next-dev-server.js:751:28)
    at async DevServer.handleRequest (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:322:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\load-components.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\next-server.js',
    at async pipe.req.req (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:1075:30)
    at async DevServer.pipe (D:\Projects\others\nextjs-starter\node_modules\next\dist\server\base-server.js:407:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\load-components.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\next-server.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\dev\\next-dev-server.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\next.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\cli\\next-dev.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\lib\\commands.js',
    'D:\\Projects\\others\\nextjs-starter\\node_modules\\next\\dist\\bin\\next'
  ]
}
```

**Comment by bmarshall511** [comment]
@mrEckendonk Please wait for the first beta release unless you'd like to contribute some PRs
